### ISSUE TITLE
stackblitz example request

### ISSUE THREAD

**Issue by st-clair-clarke** [mzeiher/ce-decorators#6]
Hi, could you please make a stackblitz app to demo usage of ce-decorators? I am requesting because angular is tellling me:
1. There is no template in my component
2. My component is not registered in any module

![webcmp](https://user-images.githubusercontent.com/3227590/56657516-385fa380-6666-11e9-95b3-cbf83ba9e121.jpg)

Thanks

**Comment by mzeiher** [comment]
actually this is a bug in the angular tooling you have installed, due to the same name of the Component decorator ng thinks its an angular component (maybe try to import the component with an alias `import {Component as CEComponent} from 'ce-decorators' )

ce-decorators should work in angular (see https://stackblitz.com/edit/angular-pgmfsw)

**Comment by st-clair-clarke** [comment]
Hi, corrected as per suggestion. However, in your stackblitz, why is the custom element not displayed. All I see is shown in the attached graphic.
![stackblitz](https://user-images.githubusercontent.com/3227590/56697135-ed707b00-66bb-11e9-80e4-cb7b64363e2c.jpg)

**Comment by mzeiher** [comment]
actually, the thing you are seeing **is** the custom element (the element which counts up)

**Comment by st-clair-clarke** [comment]
Sorry. My mistake.
Thanks
